// functions/linkAccount.ts
// Consolidated account linking - handles both parent-initiated and code-based linking
// Replaces: linkUserToPerson.ts and linkUserWithCode.ts

import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';
import {
  requireAuth,
  getUserFamilyId,
  getFamily,
  validateFamilyAccess,
  validateLinkingCode,
  sanitizeCode,
  isParent,
  isExpired,
  checkRateLimit,
  errorResponseWithCode,
  successResponse,
  logError,
  logInfo,
  parseRequestBody,
  HEADERS,
  LINK_ERROR_CODES,
} from './lib/shared-utils.ts';

/**
 * Parent-initiated account linking
 * Links a specific person to the current user's account
 */
async function handleParentLink(base44: any, user: any, personId: string) {
  if (!personId) {
    return errorResponseWithCode('Person ID is required', LINK_ERROR_CODES.LINK_FAILED);
  }

  // Rate limit
  const rateLimit = checkRateLimit(user.id, 'link_parent', 10, 5 * 60 * 1000);
  if (!rateLimit.allowed) {
    return errorResponseWithCode(
      'Too many linking attempts. Please try again later.',
      LINK_ERROR_CODES.RATE_LIMITED,
      429
    );
  }

  // Get person record
  let person;
  try {
    person = await base44.asServiceRole.entities.Person.get(personId);
  } catch {
    return errorResponseWithCode('Person not found or not accessible', LINK_ERROR_CODES.PERSON_NOT_FOUND, 404);
  }

  // Verify user is in the same family
  const familyCheck = validateFamilyAccess(user, person.family_id);
  if (!familyCheck.valid) {
    return errorResponseWithCode(familyCheck.error, LINK_ERROR_CODES.ACCESS_DENIED, 403);
  }

  // Check if person is already linked to another user
  if (person.linked_user_id && person.linked_user_id !== user.id) {
    return errorResponseWithCode(
      'This family member is already linked to another account',
      LINK_ERROR_CODES.ALREADY_LINKED
    );
  }

  // Check if user is already linked to another person
  const existingLink = await base44.asServiceRole.entities.Person.filter({
    linked_user_id: user.id,
    family_id: person.family_id,
  });

  if (existingLink.length > 0 && existingLink[0].id !== personId) {
    return errorResponseWithCode(
      'Your account is already linked to another family member',
      LINK_ERROR_CODES.USER_ALREADY_LINKED
    );
  }

  // Link the user to the person
  try {
    await base44.asServiceRole.entities.Person.update(personId, {
      linked_user_id: user.id,
      updated_at: new Date().toISOString(),
    });

    await base44.auth.updateMe({
      linked_person_id: personId,
    });
  } catch (linkError) {
    logError('linkAccount', linkError, {
      context: 'handleParentLink_link_operation',
      userId: user.id,
      personId,
    });

    // Attempt to revert Person record
    try {
      await base44.asServiceRole.entities.Person.update(personId, {
        linked_user_id: person.linked_user_id || null,
        updated_at: new Date().toISOString(),
      });
    } catch (rollbackError) {
      logError('linkAccount', rollbackError, { context: 'rollback_failed' });
    }

    return errorResponseWithCode(
      'Failed to complete account linking. Please try again.',
      LINK_ERROR_CODES.LINK_FAILED,
      500
    );
  }

  logInfo('linkAccount', 'Parent linked account to person', {
    userId: user.id,
    personId,
  });

  return successResponse({
    message: 'Successfully linked your account!',
    personId,
    personName: person.name,
  });
}

/**
 * Code-based account linking
 * Allows user to link using a linking code
 */
async function handleCodeLink(base44: any, user: any, linkingCode: string) {
  // Validate user has a family
  const familyId = getUserFamilyId(user);
  if (!familyId) {
    return errorResponseWithCode(
      'You must be part of a family to link accounts',
      LINK_ERROR_CODES.NO_FAMILY
    );
  }

  // Rate limit
  const rateLimit = checkRateLimit(user.id, 'link_code', 10, 5 * 60 * 1000);
  if (!rateLimit.allowed) {
    return errorResponseWithCode(
      'Too many code attempts. Please try again later.',
      LINK_ERROR_CODES.RATE_LIMITED,
      429
    );
  }

  // Validate code format
  const { valid, code: sanitizedCode, error } = sanitizeCode(linkingCode);
  if (!valid) {
    return errorResponseWithCode(error, LINK_ERROR_CODES.INVALID_CODE);
  }

  // Get family
  const { family } = await getFamily(base44, familyId);
  if (!family) {
    return errorResponseWithCode('Family not found', LINK_ERROR_CODES.FAMILY_NOT_FOUND, 404);
  }

  // Validate linking code - check user-specific codes first, then family-wide code
  const codeValidation = validateLinkingCode(family, sanitizedCode);
  if (!codeValidation.valid) {
    // Fallback: check family-wide linking code (generated by familyLinking.ts)
    const familyCodeValid =
      family.linking_code &&
      family.linking_code.toUpperCase() === sanitizedCode &&
      family.linking_code_expires &&
      !isExpired(family.linking_code_expires);

    if (!familyCodeValid) {
      return errorResponseWithCode(codeValidation.error, LINK_ERROR_CODES.INVALID_CODE);
    }
  }

  // Get all unlinked people in the family
  const allPeople = await base44.asServiceRole.entities.Person.filter({
    family_id: familyId,
  });

  const unlinkedPeople = allPeople.filter((p) => !p.linked_user_id);

  if (unlinkedPeople.length === 0) {
    return errorResponseWithCode(
      'No available family member profiles to link',
      LINK_ERROR_CODES.NO_UNLINKED_PEOPLE
    );
  }

  // Check if user is already linked to a person
  const existingLink = await base44.asServiceRole.entities.Person.filter({
    linked_user_id: user.id,
    family_id: familyId,
  });

  if (existingLink.length > 0) {
    const linkedPerson = existingLink[0];
    return successResponse({
      message: 'Account already linked to this family member',
      personId: linkedPerson.id,
      personName: linkedPerson.name,
      alreadyLinked: true,
    });
  }

  // If only one unlinked person, link automatically
  let personToLink;
  if (unlinkedPeople.length === 1) {
    personToLink = unlinkedPeople[0];
  } else {
    // Return list for user to choose
    return successResponse({
      needsSelection: true,
      unlinkedPeople: unlinkedPeople.map((p) => ({
        id: p.id,
        name: p.name,
        role: p.role,
        avatar_color: p.avatar_color,
      })),
    });
  }

  // Link the user to the person
  try {
    await base44.asServiceRole.entities.Person.update(personToLink.id, {
      linked_user_id: user.id,
      updated_at: new Date().toISOString(),
    });

    await base44.auth.updateMe({
      linked_person_id: personToLink.id,
    });
  } catch (linkError) {
    logError('linkAccount', linkError, {
      context: 'handleCodeLink_link_operation',
      userId: user.id,
      personId: personToLink.id,
    });

    // Attempt to revert Person record
    try {
      await base44.asServiceRole.entities.Person.update(personToLink.id, {
        linked_user_id: null,
        updated_at: new Date().toISOString(),
      });
    } catch (rollbackError) {
      logError('linkAccount', rollbackError, { context: 'rollback_failed' });
    }

    return errorResponseWithCode(
      'Failed to complete account linking. Please try again.',
      LINK_ERROR_CODES.LINK_FAILED,
      500
    );
  }

  logInfo('linkAccount', 'User linked account with code', {
    userId: user.id,
    personId: personToLink.id,
  });

  return successResponse({
    message: 'Successfully linked your account!',
    personId: personToLink.id,
    personName: personToLink.name,
    alreadyLinked: false,
  });
}

/**
 * Manual person selection after code validation
 */
async function handleManualSelection(base44: any, user: any, personId: string) {
  const familyId = getUserFamilyId(user);
  if (!familyId) {
    return errorResponseWithCode('You must be part of a family', LINK_ERROR_CODES.NO_FAMILY);
  }

  // Rate limit
  const rateLimit = checkRateLimit(user.id, 'link_select', 10, 5 * 60 * 1000);
  if (!rateLimit.allowed) {
    return errorResponseWithCode(
      'Too many selection attempts. Please try again later.',
      LINK_ERROR_CODES.RATE_LIMITED,
      429
    );
  }

  // Get person and verify they're unlinked
  let person;
  try {
    person = await base44.asServiceRole.entities.Person.get(personId);
  } catch {
    return errorResponseWithCode('Person not found', LINK_ERROR_CODES.PERSON_NOT_FOUND, 404);
  }

  // Verify same family
  const familyCheck = validateFamilyAccess(user, person.family_id);
  if (!familyCheck.valid) {
    return errorResponseWithCode(familyCheck.error, LINK_ERROR_CODES.ACCESS_DENIED, 403);
  }

  // Check if person is already linked
  if (person.linked_user_id) {
    return errorResponseWithCode(
      'This family member is already linked to another account',
      LINK_ERROR_CODES.ALREADY_LINKED
    );
  }

  // Check if user is already linked
  const existingLink = await base44.asServiceRole.entities.Person.filter({
    linked_user_id: user.id,
    family_id: familyId,
  });

  if (existingLink.length > 0) {
    return errorResponseWithCode(
      'Your account is already linked to another family member',
      LINK_ERROR_CODES.USER_ALREADY_LINKED
    );
  }

  // Link the user to the person
  try {
    await base44.asServiceRole.entities.Person.update(personId, {
      linked_user_id: user.id,
      updated_at: new Date().toISOString(),
    });

    await base44.auth.updateMe({
      linked_person_id: personId,
    });
  } catch (linkError) {
    logError('linkAccount', linkError, {
      context: 'handleManualSelection_link_operation',
      userId: user.id,
      personId,
    });

    // Attempt to revert Person record
    try {
      await base44.asServiceRole.entities.Person.update(personId, {
        linked_user_id: null,
        updated_at: new Date().toISOString(),
      });
    } catch (rollbackError) {
      logError('linkAccount', rollbackError, { context: 'rollback_failed' });
    }

    return errorResponseWithCode(
      'Failed to complete account linking. Please try again.',
      LINK_ERROR_CODES.LINK_FAILED,
      500
    );
  }

  logInfo('linkAccount', 'User completed manual person selection', {
    userId: user.id,
    personId,
  });

  return successResponse({
    message: 'Successfully linked your account!',
    personId,
    personName: person.name,
  });
}

/**
 * Main handler
 */
Deno.serve(async (req) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: HEADERS });
  }

  const base44 = createClientFromRequest(req);

  try {
    // Authentication check
    const { user, error: authError } = await requireAuth(base44);
    if (authError) return authError;

    // Parse request body
    const { data: body, error: parseError } = await parseRequestBody(req);
    if (parseError) return parseError;

    const { method, personId, linkingCode } = body;

    // Route to appropriate handler
    switch (method) {
      case 'parent_link':
        // Parent linking their own account to a person
        if (!isParent(user)) {
          return errorResponseWithCode(
            'Only parents can perform this action',
            LINK_ERROR_CODES.PARENT_REQUIRED,
            403
          );
        }
        return await handleParentLink(base44, user, personId);

      case 'code_link':
        // User linking with a code
        if (!linkingCode) {
          return errorResponseWithCode(
            'Linking code required for code-based linking',
            LINK_ERROR_CODES.INVALID_CODE
          );
        }
        return await handleCodeLink(base44, user, linkingCode);

      case 'select_person':
        // User selecting from multiple unlinked people
        if (!personId) {
          return errorResponseWithCode(
            'Person ID required for manual selection',
            LINK_ERROR_CODES.LINK_FAILED
          );
        }
        return await handleManualSelection(base44, user, personId);

      default:
        return errorResponseWithCode(
          'Invalid method. Use "parent_link", "code_link", or "select_person"',
          LINK_ERROR_CODES.LINK_FAILED
        );
    }
  } catch (error) {
    logError('linkAccount', error);
    return errorResponseWithCode(
      'An internal server error occurred',
      LINK_ERROR_CODES.SERVER_ERROR,
      500
    );
  }
});
